# Generated by Django 5.2.4 on 2025-08-02 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the trip, e.g., Bali Trip', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the trip')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the trip was created')),
                ('start_date', models.DateField(help_text='Start date of the trip')),
                ('end_date', models.DateField(help_text='End date of the trip')),
                ('successful', models.BooleanField(default=False, help_text='Indicates if the trip was successful')),
                ('members', models.ManyToManyField(help_text='Users participating in the trip', related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
