# Generated by Django 5.2.4 on 2025-08-02 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0006_userprofile_portfolio_userprofile_youtube_channel'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=False, help_text='User who created the trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='manage.userprofile'),
        ),
    ]
