# Generated by Django 5.2.4 on 2025-08-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_trip_options_remove_trip_user_trip_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the trip', null=True, upload_to='trips/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', help_text='Current status of the trip', max_length=20),
        ),
    ]
