# Generated by Django 5.2.4 on 2025-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_remove_userprofile_dob_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
