# Generated by Django 5.2.4 on 2025-08-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_userprofile_is_private_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_locatioin',
            field=models.BooleanField(default=True),
        ),
    ]
