# Generated by Django 5.2.4 on 2025-08-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0004_userprofile_show_locatioin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='show_locatioin',
            new_name='show_location',
        ),
    ]
