# Generated by Django 5.2.4 on 2025-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0005_rename_show_locatioin_userprofile_show_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.URLField(blank=True, help_text='Link to your portfolio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_channel',
            field=models.URLField(blank=True, help_text='Link to your YouTube channel'),
        ),
    ]
