# Generated by Django 5.2.4 on 2025-08-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('travel', 'Travel Story'), ('photo', 'Photo Gallery'), ('tip', 'Travel Tip'), ('review', 'Review'), ('itinerary', 'Itinerary')], default='travel', max_length=20),
        ),
        migrations.AddField(
            model_name='postimage',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
